### ISSUE TITLE
Error: Cannot write to fan controller

### ISSUE THREAD

**Issue by mgytr** [GnomedDev/T2FanRD#1]
Hi, I installed EndeavourOS (T2Linux), but i noticed it's extremely loud. I did go to the t2linux guide, and did try to reinstall T2FanRD, but it did not help.
Here is the full output:
> sudo systemctl enable --now t2fanrd
Job for t2fanrd.service failed because the control process exited with error code.
See "systemctl status t2fanrd.service" and "journalctl -xeu t2fanrd.service" for details.
> sudo t2fanrd 
Found fan: FanController {
    manual_file: File {
        fd: 3,
        path: "/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:85/APP0001:00/fan1_manual",
        read: false,
        write: true,
    },
    output_file: File {
        fd: 4,
        path: "/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:85/APP0001:00/fan1_output",
        read: false,
        write: true,
    },
    config: FanConfig {
        low_temp: 55,
        high_temp: 75,
        speed_curve: Linear,
        always_full_speed: false,
    },
    min_speed: 2700,
    max_speed: 8000,
}

Error: Cannot write to fan controller

**Comment by GnomedDev** [comment]
This is most likely a driver issue, please try with the old `t2fand` as I'm expecting the same error.

**Comment by mgytr** [comment]
Then i get an "Input/Output error", and i even have almost the same hardware as in this issue: https://github.com/NoaHimesaka1873/t2fand/issues/1. And the maintainer said what it is a applesmc error and that the issue starter needs to enter his/her discord, but i can't seem to find it

**Comment by GnomedDev** [comment]
The discord is https://discord.gg/Jayz5f5, I'll close this now.

**Comment by CaptainMorgan12** [comment]
what is the actual physical address of the device I would like to just echo the device the RPM manually so they run at say 900rpm:

<pre><font color="#12488B"><b>/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00</b></font>$ ls
adr        <font color="#12488B"><b>device:04</b></font>  <font color="#12488B"><b>device:09</b></font>  <font color="#12488B"><b>device:0e</b></font>  <font color="#12488B"><b>device:16</b></font>  <font color="#12488B"><b>device:21</b></font>  modalias       <font color="#2AA1B3"><b>subsystem</b></font>
<font color="#12488B"><b>device:00</b></font>  <font color="#12488B"><b>device:05</b></font>  <font color="#12488B"><b>device:0a</b></font>  <font color="#12488B"><b>device:11</b></font>  <font color="#12488B"><b>device:18</b></font>  <font color="#12488B"><b>device:22</b></font>  path           uevent
<font color="#12488B"><b>device:01</b></font>  <font color="#12488B"><b>device:06</b></font>  <font color="#12488B"><b>device:0b</b></font>  <font color="#12488B"><b>device:13</b></font>  <font color="#12488B"><b>device:1a</b></font>  <font color="#12488B"><b>device:23</b></font>  <font color="#2AA1B3"><b>physical_node</b></font>  uid
<font color="#12488B"><b>device:02</b></font>  <font color="#12488B"><b>device:07</b></font>  <font color="#12488B"><b>device:0c</b></font>  <font color="#12488B"><b>device:14</b></font>  <font color="#12488B"><b>device:1f</b></font>  <font color="#12488B"><b>device:24</b></font>  <font color="#12488B"><b>PNP0C02:01</b></font>     <font color="#12488B"><b>wakeup</b></font>
<font color="#12488B"><b>device:03</b></font>  <font color="#12488B"><b>device:08</b></font>  <font color="#12488B"><b>device:0d</b></font>  <font color="#12488B"><b>device:15</b></font>  <font color="#12488B"><b>device:20</b></font>  hid        <font color="#12488B"><b>power</b></font>
</pre>

**Comment by sharpenedblade** [comment]
This is a kernel bug so it can't be fixed by t2fanrd. You can open a issue for the t2linux patches repo, but we do not have any fixes right now.
